-- Migration: fondos, carteras, operaciones
-- Generated programmatically to avoid Markdown link corruption

CREATE TABLE IF NOT EXISTS "fondos" (
  "id"              SERIAL PRIMARY KEY,
  "nombre"          VARCHAR(255) NOT NULL,
  "dni"             VARCHAR(20),
  "empresa"         VARCHAR(255),
  "nif"             VARCHAR(20),
  "imagen"          VARCHAR(255),
  "direccion"       VARCHAR(255),
  "municipio"       VARCHAR(100),
  "provincia"       VARCHAR(100),
  "codigo_postal"   VARCHAR(10),
  "emails"          JSONB NOT NULL DEFAULT '[]',
  "telefonos"       JSONB NOT NULL DEFAULT '[]',
  "contactos"       JSONB NOT NULL DEFAULT '[]',
  "comision_gestion" NUMERIC(6,4),
  "notas"           TEXT,
  "created_at"      TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at"      TIMESTAMP NOT NULL DEFAULT NOW(),
  "creator_id"      TEXT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "carteras" (
  "id"                  SERIAL PRIMARY KEY,
  "fondo_id"            INTEGER NOT NULL REFERENCES "fondos"("id") ON DELETE CASCADE,
  "cartera_name"        VARCHAR(100) NOT NULL,
  "excel_file"          VARCHAR(50),
  "asset_manager"       VARCHAR(100),
  "oficina_responsable" VARCHAR(100),
  "comision_gestion"    NUMERIC(6,4),
  "map_items"           JSONB NOT NULL DEFAULT '[]',
  "created_at"          TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at"          TIMESTAMP NOT NULL DEFAULT NOW(),
  "fecha_definicion"    DATE
);

CREATE TABLE IF NOT EXISTS "operaciones" (
  "id"                      SERIAL PRIMARY KEY,
  "fondo_id"                INTEGER REFERENCES "fondos"("id") ON DELETE SET NULL,
  "cartera_id"              INTEGER REFERENCES "carteras"("id") ON DELETE SET NULL,
  "asset_manager"           VARCHAR(100),
  "oficina_responsable"     VARCHAR(100),
  "expediente_id"           VARCHAR(50),
  "prestamo_id"             VARCHAR(50),
  "npl_reo"                 VARCHAR(20),
  "deudor_nombre"           VARCHAR(100),
  "fecha_alta"              DATE,
  "deuda"                   NUMERIC(14,2),
  "precio_venta_mercado"    NUMERIC(14,2),
  "rango_lien_prestamo"     VARCHAR(10),
  "valor_tasacion_subasta"  NUMERIC(14,2),
  "property_id"             VARCHAR(50),
  "property_tipo"           VARCHAR(100),
  "property_tipo_ocupacion" VARCHAR(100),
  "es_vpo"                  BOOLEAN,
  "es_vulnerable"           VARCHAR(100),
  "provincia"               VARCHAR(50),
  "municipio"               VARCHAR(50),
  "cod_postal"              VARCHAR(10),
  "direccion_completa"      VARCHAR(100),
  "referencia_catastral"    VARCHAR(10),
  "idufir"                  VARCHAR(50),
  "parcel"                  VARCHAR(10),
  "superficie_const"        NUMERIC(10,2),
  "superficie_util"         NUMERIC(10,2),
  "superficie_finca"        NUMERIC(10,2),
  "superficie_registral"    NUMERIC(10,2),
  "libro"                   VARCHAR(50),
  "tomo"                    VARCHAR(50),
  "finca"                   VARCHAR(50),
  "folio"                   VARCHAR(50),
  "latitud"                 NUMERIC(12,8),
  "longitud"                NUMERIC(12,8),
  "any_construccion"        INTEGER,
  "proc_legal"              VARCHAR(50),
  "proc_legal_tipo"         VARCHAR(50),
  "proc_legal_fase"         VARCHAR(50),
  "proc_legal_numero"       VARCHAR(50),
  "proc_legal_court"        VARCHAR(50),
  "proc_legal_estado"       VARCHAR(50),
  "registro_provincia"      VARCHAR(50),
  "registro_ciudad"         VARCHAR(50),
  "registro_numero"         VARCHAR(50),
  "created_at"              TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at"              TIMESTAMP NOT NULL DEFAULT NOW(),
  "fecha_tratamiento"       DATE
);
