import { z } from 'zod';

// ── Estrategia definitiva ─────────────────────────────────────────────────────
// El form RHF trabaja siempre con strings (lo que los inputs HTML producen).
// El schema convierte y valida solo al momento de guardar en el server action.
// Esto evita la incompatibilidad de tipos entre RHF y zodResolver con transforms.

const optStr = (max: number) =>
  z.string().max(max).nullish().transform(v => v ?? null);

const optNum = z.preprocess(
  v => (v === '' || v === null || v === undefined ? null : Number(v)),
  z.number().nullable()
) as z.ZodType<number | null | undefined>;

const optDate = z.string().nullish().transform(v => v || null);

const optInt = z.preprocess(
  v => (v === '' || v === null || v === undefined ? null : parseInt(String(v), 10)),
  z.number().int().nullable()
) as z.ZodType<number | null | undefined>;

const optBool = z.preprocess(
  v => (v === '' || v === undefined ? null : v),
  z.boolean().nullable()
) as z.ZodType<boolean | null | undefined>;

const optEnum = <T extends [string, ...string[]]>(values: T) =>
  z.preprocess(
    v => (v === '' || v === undefined ? null : v),
    z.enum(values).nullable()
  ) as z.ZodType<T[number] | null | undefined>;

// ── Schema de GUARDADO (server action) ───────────────────────────────────────
export const EnrichmentSchema = z.object({
  sellerReference: optStr(100),
  originalLender:  optStr(255),
  idufir:          optStr(50),
  cru:             optStr(50),

  fechaOriginacion:       optDate,
  fechaImpago:            optDate,
  fechaClasificacionNpl:  optDate,
  fechaUltimoPago:        optDate,
  fechaVencimiento:       optDate,
  fechaCompraCartera:     optDate,
  fechaInicioAccionLegal: optDate,
  principalOriginal:   optNum,
  principalPendiente:  optNum,
  interesesDevengados: optNum,
  deudaTotal:          optNum,
  gbv:                 optNum,
  tipoInteres:         optNum,
  cuotaMensual:        optNum,
  ltv:                 optNum,
  mesesImpago:         optInt,
  tasacionOriginal:      optNum,
  tasacionActual:        optNum,
  fechaTasacion:         optDate,
  valorMercado:          optNum,
  valorEjecucionForzosa: optNum,
  precioSubasta:         optNum,
  precioVenta:           optNum,

  propertyId:   optStr(50),
  tipoInmueble: optStr(100),
  comunidadAutonoma: optStr(100),
  provincia:         optStr(100),
  municipio:         optStr(100),
  municipioId:       optInt,
  codPostal:         optStr(10),
  tipoVia:           optStr(50),
  nombreVia:         optStr(200),
  numero:            optStr(20),
  bloque:            optStr(20),
  planta:            optStr(20),
  puerta:            optStr(20),
  latitud:           optNum,
  longitud:          optNum,
  referenciaCatastral: optStr(25),
  usoCatastral:        optStr(100),
  valorRefCatastral:   optNum,
  valorCatastral:      optNum,
  superficieConst:     optNum,
  superficieUtil:      optNum,
  superficieParcela:   optNum,
  zonasComunes:        optNum,
  anyConstruccion:     optInt,
  idufirReg:         optStr(50),
  fincaRegistral:    optStr(50),
  libro:             optStr(50),
  tomo:              optStr(50),
  folio:             optStr(50),
  registroProvincia: optStr(100),
  registroCiudad:    optStr(100),
  registroNumero:    optStr(50),
  dormitorios:           optInt,
  banyos:                optInt,
  garaje:                optBool,
  plazasGaraje:          optInt,
  trastero:              optBool,
  ascensor:              optBool,
  jardin:                optBool,
  piscina:               optBool,
  estadoConservacion:    optEnum(['nuevo', 'buen_estado', 'a_reformar', 'ruinoso']),
  certificadoEnergetico: optEnum(['A', 'B', 'C', 'D', 'E', 'F', 'G']),
  estadoOcupacion:           optEnum(['vacio', 'ocupado', 'irregular']),
  tipoOcupante:              optEnum(['propietario', 'inquilino', 'tercero', 'okupa']),
  rentaMensual:              optNum,
  vencimientoAlquiler:       optDate,
  restriccionesUrbanisticas: optStr(2000),

  estadoLegal:         optEnum(['prejudicial', 'judicial', 'finalizado']),
  faseJudicial:        optEnum(['monitorio', 'ordinario', 'ejecucion']),
  subfaseJudicial:     optStr(100),
  juzgado:             optStr(255),
  partidoJudicial:     optStr(100),
  numeroProcedimiento: optStr(50),
  fechaSubasta:        optDate,
  numeroSubasta:       optStr(20),
  fechaAdjudicacion:   optDate,
  tipoAdjudicacion:    optEnum(['acreedor', 'tercero', 'desierta']),
  totalCargas:           optNum,
  cargasPreferentes:     optNum,
  cargasPosteriores:     optNum,
  ibiPendiente:          optNum,
  comunidadPendiente:    optNum,
  suministrosPendientes: optNum,
  embargos:              optStr(2000),
  usufructo:             optBool,
  servidumbres:          optStr(2000),
  tipoGarantia:          optStr(50),
  rangoGarantia:         optStr(10),
  garantiaCruzada:       optBool,

  numeroDeudores:   optInt,
  tieneAvalistas:   optBool,
  provinciaDeudor:  optStr(100),
  situacionLaboral: optEnum(['empleado', 'desempleado', 'autonomo', 'jubilado', 'otro']),
  nivelIngresos:    optEnum(['alto', 'medio', 'bajo']),
  ratingSolvencia:  optStr(20),
  notasDeudores:    optStr(4000),

  estrategiaRecuperacion: optEnum(['reo', 'venta_directa', 'reestructuracion', 'dacion', 'otro']),
  prioridad:              optEnum(['alta', 'media', 'baja']),
  oportunidadInversion:   optStr(50),
  recuperacionEsperada:   optNum,
  plazoRecuperacion:      optInt,
  riesgoRating:           optEnum(['alto', 'medio', 'bajo']),
  clusterGeografico:      optStr(100),
  gestorAsignado:         optStr(100),
  notasObservaciones:     optStr(4000),
  estadoDocumentacion:    optEnum(['completa', 'incompleta', 'pendiente']),
  escrituraDisponible:    optBool,
  antiguedadNotaSimple:   optDate,
});

// ── Schema de FORM (RHF) — solo strings y booleans, sin transforms ────────────
// Este es el tipo que usa useForm<> — los inputs HTML siempre producen strings
export const EnrichmentFormSchema = z.object({
  sellerReference: z.string().nullish(),
  originalLender:  z.string().nullish(),
  idufir:          z.string().nullish(),
  cru:             z.string().nullish(),

  fechaOriginacion:       z.string().nullish(),
  fechaImpago:            z.string().nullish(),
  fechaClasificacionNpl:  z.string().nullish(),
  fechaUltimoPago:        z.string().nullish(),
  fechaVencimiento:       z.string().nullish(),
  fechaCompraCartera:     z.string().nullish(),
  fechaInicioAccionLegal: z.string().nullish(),
  principalOriginal:   z.string().nullish(),
  principalPendiente:  z.string().nullish(),
  interesesDevengados: z.string().nullish(),
  deudaTotal:          z.string().nullish(),
  gbv:                 z.string().nullish(),
  tipoInteres:         z.string().nullish(),
  cuotaMensual:        z.string().nullish(),
  ltv:                 z.string().nullish(),
  mesesImpago:         z.string().nullish(),
  tasacionOriginal:      z.string().nullish(),
  tasacionActual:        z.string().nullish(),
  fechaTasacion:         z.string().nullish(),
  valorMercado:          z.string().nullish(),
  valorEjecucionForzosa: z.string().nullish(),
  precioSubasta:         z.string().nullish(),
  precioVenta:           z.string().nullish(),

  propertyId:   z.string().nullish(),
  tipoInmueble: z.string().nullish(),
  comunidadAutonoma: z.string().nullish(),
  provincia:         z.string().nullish(),
  municipio:         z.string().nullish(),
  municipioId:       z.string().nullish(),
  codPostal:         z.string().nullish(),
  tipoVia:           z.string().nullish(),
  nombreVia:         z.string().nullish(),
  numero:            z.string().nullish(),
  bloque:            z.string().nullish(),
  planta:            z.string().nullish(),
  puerta:            z.string().nullish(),
  latitud:           z.string().nullish(),
  longitud:          z.string().nullish(),
  referenciaCatastral: z.string().nullish(),
  usoCatastral:        z.string().nullish(),
  valorRefCatastral:   z.string().nullish(),
  valorCatastral:      z.string().nullish(),
  superficieConst:     z.string().nullish(),
  superficieUtil:      z.string().nullish(),
  superficieParcela:   z.string().nullish(),
  zonasComunes:        z.string().nullish(),
  anyConstruccion:     z.string().nullish(),
  idufirReg:         z.string().nullish(),
  fincaRegistral:    z.string().nullish(),
  libro:             z.string().nullish(),
  tomo:              z.string().nullish(),
  folio:             z.string().nullish(),
  registroProvincia: z.string().nullish(),
  registroCiudad:    z.string().nullish(),
  registroNumero:    z.string().nullish(),
  dormitorios:   z.string().nullish(),
  banyos:        z.string().nullish(),
  garaje:        z.boolean().nullish(),
  plazasGaraje:  z.string().nullish(),
  trastero:      z.boolean().nullish(),
  ascensor:      z.boolean().nullish(),
  jardin:        z.boolean().nullish(),
  piscina:       z.boolean().nullish(),
  estadoConservacion:    z.string().nullish(),
  certificadoEnergetico: z.string().nullish(),
  estadoOcupacion:           z.string().nullish(),
  tipoOcupante:              z.string().nullish(),
  rentaMensual:              z.string().nullish(),
  vencimientoAlquiler:       z.string().nullish(),
  restriccionesUrbanisticas: z.string().nullish(),

  estadoLegal:         z.string().nullish(),
  faseJudicial:        z.string().nullish(),
  subfaseJudicial:     z.string().nullish(),
  juzgado:             z.string().nullish(),
  partidoJudicial:     z.string().nullish(),
  numeroProcedimiento: z.string().nullish(),
  fechaSubasta:        z.string().nullish(),
  numeroSubasta:       z.string().nullish(),
  fechaAdjudicacion:   z.string().nullish(),
  tipoAdjudicacion:    z.string().nullish(),
  totalCargas:           z.string().nullish(),
  cargasPreferentes:     z.string().nullish(),
  cargasPosteriores:     z.string().nullish(),
  ibiPendiente:          z.string().nullish(),
  comunidadPendiente:    z.string().nullish(),
  suministrosPendientes: z.string().nullish(),
  embargos:              z.string().nullish(),
  usufructo:             z.boolean().nullish(),
  servidumbres:          z.string().nullish(),
  tipoGarantia:          z.string().nullish(),
  rangoGarantia:         z.string().nullish(),
  garantiaCruzada:       z.boolean().nullish(),

  numeroDeudores:   z.string().nullish(),
  tieneAvalistas:   z.boolean().nullish(),
  provinciaDeudor:  z.string().nullish(),
  situacionLaboral: z.string().nullish(),
  nivelIngresos:    z.string().nullish(),
  ratingSolvencia:  z.string().nullish(),
  notasDeudores:    z.string().nullish(),

  estrategiaRecuperacion: z.string().nullish(),
  prioridad:              z.string().nullish(),
  oportunidadInversion:   z.string().nullish(),
  recuperacionEsperada:   z.string().nullish(),
  plazoRecuperacion:      z.string().nullish(),
  riesgoRating:           z.string().nullish(),
  clusterGeografico:      z.string().nullish(),
  gestorAsignado:         z.string().nullish(),
  notasObservaciones:     z.string().nullish(),
  estadoDocumentacion:    z.string().nullish(),
  escrituraDisponible:    z.boolean().nullish(),
  antiguedadNotaSimple:   z.string().nullish(),
});

// EnrichmentFormValues — tipo del form RHF (strings)
export type EnrichmentFormValues = z.infer<typeof EnrichmentFormSchema>;
// EnrichmentInput — tipo de salida tras parse (números, enums correctos)
export type EnrichmentInput = z.output<typeof EnrichmentSchema>;
